In [5]:
import pandas as pd

df = pd.read_csv("/content/superstore.csv")
df.head()

,RowID,OrderID,OrderDate,ShipDate,ShipMode,CustomerID,CustomerName,Segment,Country,City,...,PostalCode,Region,ProductID,Category,SubCategory,ProductName,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,4/26/1982,4/26/1985,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,4/26/1982,4/26/1985,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,4/25/1933,4/25/1937,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,4/22/1988,4/22/1995,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,4/22/1988,4/22/1995,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [7]:
df.columns

Index(['RowID', 'OrderID', 'OrderDate', 'ShipDate', 'ShipMode', 'CustomerID',
       'CustomerName', 'Segment', 'Country', 'City', 'State', 'PostalCode',
       'Region', 'ProductID', 'Category', 'SubCategory', 'ProductName',
       'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

In [8]:
df.dtypes

RowID             int64
OrderID          object
OrderDate        object
ShipDate         object
ShipMode         object
CustomerID       object
CustomerName     object
Segment          object
Country          object
City             object
State            object
PostalCode        int64
Region           object
ProductID        object
Category         object
SubCategory      object
ProductName      object
Sales           float64
Quantity          int64
Discount        float64
Profit          float64
dtype: object

In [11]:
import pandas as pd

def parse_date(x):
    try:
        return pd.to_datetime(x, format='%m/%d/%Y')
    except:
        try:
            return pd.to_datetime('1899-12-30') + pd.to_timedelta(int(x), 'D')
        except:
            return pd.NaT

In [13]:
df['OrderDate'] = df['OrderDate'].apply(parse_date)
df['ShipDate']  = df['ShipDate'].apply(parse_date)

In [14]:
df[['OrderDate','ShipDate']].head(10)
df.dtypes

RowID                    int64
OrderID                 object
OrderDate       datetime64[ns]
ShipDate        datetime64[ns]
ShipMode                object
CustomerID              object
CustomerName            object
Segment                 object
Country                 object
City                    object
State                   object
PostalCode               int64
Region                  object
ProductID               object
Category                object
SubCategory             object
ProductName             object
Sales                  float64
Quantity                 int64
Discount               float64
Profit                 float64
dtype: object

In [15]:
orders = pd.read_csv("/content/orders.csv")
customers = pd.read_csv("/content/customers.csv")
products = pd.read_csv("/content/products.csv")

In [16]:
orders['OrderDate'] = orders['OrderDate'].apply(parse_date)
orders['ShipDate'] = orders['ShipDate'].apply(parse_date)

In [17]:
order_summary = (
    orders
    .merge(customers, on="CustomerID", how="left")
    .merge(products, on="ProductID", how="left")
    .groupby(
        ['OrderID', 'OrderDate', 'ShipDate', 'CustomerName', 'Region', 'Segment', 'Category', 'SubCategory'],
        as_index=False
    )
    .agg(
        TotalSales = ('Sales', 'sum'),
        TotalProfit = ('Profit', 'sum'),
        TotalQuantity = ('Quantity', 'sum'),
        ProfitMargin = ('Profit', lambda x: round(x.sum() / max(orders.loc[x.index,'Sales'].sum(), 1), 3)),
        AvgDiscount = ('Discount', 'mean')
    )
)

In [18]:
order_summary['AvgDiscount'] = order_summary['AvgDiscount'].round(3)

In [19]:
output_path = "/content/order_summary_cleaned.csv"
order_summary.to_csv(output_path, index=False)

In [20]:
output_path = "/content/order_summary_cleaned.csv"
order_summary.to_csv(output_path, index=False)

print(f"Cleaned order_summary CSV saved to: {output_path}")

Cleaned order_summary CSV saved to: /content/order_summary_cleaned.csv

In [21]:
df.to_csv("/content/superstore_cleaned.csv", index=False)